// <auto-generated />
namespace ILK_Protokoll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class topichistory_time_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(topichistory_time_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201408271515005_topichistory_time_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
