// <auto-generated />
namespace ILK_Protokoll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class comment_AuthorID_explicit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(comment_AuthorID_explicit));
        
        string IMigrationMetadata.Id
        {
            get { return "201409101350414_comment_AuthorID_explicit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
