// <auto-generated />
namespace ILK_Protokoll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class latest_Revision_optional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(latest_Revision_optional));
        
        string IMigrationMetadata.Id
        {
            get { return "201410151401560_latest_Revision_optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
