// <auto-generated />
namespace ILK_Protokoll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class explicit_creatorid_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(explicit_creatorid_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201409031500552_explicit_creatorid_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
