// <auto-generated />
namespace ILK_Protokoll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class approval_tristate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(approval_tristate));
        
        string IMigrationMetadata.Id
        {
            get { return "201409151502066_approval_tristate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
