// <auto-generated />
namespace ILK_Protokoll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class unreadState_marker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unreadState_marker));
        
        string IMigrationMetadata.Id
        {
            get { return "201409161228222_unreadState_marker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
