// <auto-generated />
namespace ILK_Protokoll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class lists_rp_ip_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lists_rp_ip_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201510301628243_lists_rp_ip_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
